#!/bin/sh

## installation directory
mkdir ./fathon/gsl_tmp

## install GSL
cd ./fathon/gsl
./configure --prefix=$PWD/../gsl_tmp
make
make install

## remove GSL source code
cd ..
rm -rf gsl

## copy header files and libs
mv gsl_tmp/include 3rd_party/gsl
mkdir 3rd_party/gsl/lib
mv gsl_tmp/lib/* 3rd_party/gsl/lib
rm -rf gsl_tmp